function foo(){
    try {
        return 0
    } catch (error) {
        
    }finally{
        // console.log("a")
        return 1
    }
}
console.log(foo())